name: Deploy to AWS

on: [push]  # Runs on every push

jobs:
  deploy:
    runs-on: self-hosted  # Uses the AWS EC2 instance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run on EC2
        run: |
          echo "Code deployed on AWS EC2!"
          # Add commands to restart your app, e.g., restart a web server
